---
services:
  umami:
    image: ghcr.io/umami-software/umami:latest
    ports:
      - "3055:3000"
    env_file: .env
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
